### ISSUE TITLE
Create Lambda function to push data from Kinesis stream into DynamoDB

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#1]
- DynamoDB table: UnicornSensorData
- Kinesis Stream: wildrydes
- tutorial reference: https://aws.amazon.com/getting-started/hands-on/build-serverless-real-time-data-processing-app-lambda-kinesis-s3-dynamodb-cognito-athena/4/
- build with node js 18
- aws sdk reference https://aws.amazon.com/sdk-for-javascript/

**Comment by XrosHeart05** [comment]
Take and start the issue

**Comment by XrosHeart05** [comment]
For a more flexible use of node in your environment, this is facilitated by the use of "_nvm_" (node version manager).
Below is the [link](https://github.com/coreybutler/nvm-windows/releases) where you can find the deliverable for installation in Windows environments, in the "assets" section you must select "_nvm-setup.zip_" or "_nvm-setup.exe_"

**In case** of being the **first time** that "_Node JS_" is installed in your environment you must follow the following steps:
Once downloaded unzip it for the execution as administrator of the executable "_nvm-setup.exe_" (If you downloaded the file extension "_.exe_", it is not necessary to unzip) and you must follow the normal step by step of a simple installation in Windows.

Once installed you must run a _Power Shell_ console with administrative permissions, then you must execute the following commands:

- `nvm install <nodejs version>` (recommended 18.13.0) -> This will install "_Node JS_" and the "_npm_" compatible with the installed "_Node JS_" version.

- Then run the command `nvm use 18.13.0`

**In case** you have some version of **"_Node JS_" installed** you can follow the steps in the first minutes of the following [video](https://www.youtube.com/watch?v=_G5IbsItndA)
