### ISSUE TITLE
Create local data stream

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#10]
choosethe power metric and output those results to a stream. this stream will be captured by kinesis and outputted to a database. we can then use this data with amazon sagemaker to get some insights from it and produce recommendations. This issue is just creating the data stream with the linux power metric

**Comment by tacho090** [comment]
![image](https://user-images.githubusercontent.com/26770863/232663582-405c5886-878f-464e-986d-ae35b5469178.jpeg)

**Comment by tacho090** [comment]
@XrosHeart05 take care of the following metrics:

- CPU Utilization
- Memory Usage
- Disk I/O
- Network traffic
- Latency

**Comment by XrosHeart05** [comment]
The issue is taken and started

**Comment by tacho090** [comment]
UPDATE: focus on getting data ONLY from CPU and relaying it into a stream.

**Comment by XrosHeart05** [comment]
Issue status: On the #1-cpu branch, a data generation type is being contiguous from the ```top``` command and the ``%Cpu(s)`` section.
This data is segmented and assigned to variables for their respective printouts at console level.
At console level you can see the specific cpu consumption data represented by percentages and also in a more graphical view through horizontal bars that mark the consumption of each type of process; an example is attached.
In addition this is done once per second refreshing this console "view", the idea is to use this process per second for sending data to the stream.

![imagen](https://user-images.githubusercontent.com/43551637/233818235-04db3769-b079-43f2-bf67-e5787c436093.png)

**Comment by XrosHeart05** [comment]
Average CPU core usage load is added for 1, 5, and 15 minute times; these are sent to AWS Kinesis also every 1 minute

**Comment by XrosHeart05** [comment]
Added functionality to obtain the usage time per processor core in ms versus the time of the started session in ms.
This data is sent to AWS Kinesis as well.

![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/22a2d4e0-e067-40ba-9d56-af99448d67b7)

**Comment by XrosHeart05** [comment]
Actually working in cpu usage in only one second; until work in progress

**Comment by XrosHeart05** [comment]
Memory usage statistics start to be created
![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/5c41dbe0-a4e7-48eb-9c63-1ffa3e2a1c00)

**Comment by XrosHeart05** [comment]
Current system memory consumption data is sent to Kinesis
![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/2b3f0ad2-8867-4e69-a97d-603693a57765)

**Comment by tacho090** [comment]
Is there a pull request linked to this issue? @XrosHeart05

**Comment by XrosHeart05** [comment]
Yes, currently this [PR](https://github.com/tachOrg/shell_scripts/pull/2) is still associated

**Comment by XrosHeart05** [comment]
System memory consumption data is being stored in DynamoDB.
![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/3c815c0b-301f-40a2-98e6-d8d60ccede11)

**Comment by tacho090** [comment]
Archived for reference only.
