### ISSUE TITLE
Connect data stream to aws kinesis stream

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#12]
Connect data stream from CPU usage to AWS Kinesis data stream. The objective is to have this data represented in an AWS DynamoDB table same as the unicorn exercise.

**Comment by XrosHeart05** [comment]
I take and start the task

**Comment by XrosHeart05** [comment]
Already connected the data stream, successfully sent data packet to AWS Kinesis from bash scripts.

**Comment by tacho090** [comment]
Is there a pull request for this issue? @XrosHeart05

**Comment by XrosHeart05** [comment]
Yes, this [PR](https://github.com/tachOrg/shell_scripts/pull/2)

**Comment by tacho090** [comment]
Closed due to  https://github.com/tachOrg/shell_scripts/pull/2
