### ISSUE TITLE
Complete data pipeline tutorial

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#13]
Complete data pipeline tutorial from Data Pipelines Book, starting on page 34.

**Comment by tacho090** [comment]
@XrosHeart05

**Comment by XrosHeart05** [comment]
It is taken and the task is started

**Comment by XrosHeart05** [comment]
The connection to the MySQL database is generated locally; through this connection a query is executed to obtain the data generated for the exercise, once this data is obtained a '.csv' file is generated and once this file is ready the connection to 'S3' is generated for the storage of this file; all this flow is being completed correctly.

**Comment by tacho090** [comment]
Any updates on this issue? @XrosHeart05

**Comment by XrosHeart05** [comment]
Not actually

**Comment by tacho090** [comment]
Temporarily paused due to high costs with RedShift
