### ISSUE TITLE
Visualize cpu metrics in dynamo db

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#14]
Process stream data using lambda and output result in dynamodb for one of the metrics we already have.

**Comment by XrosHeart05** [comment]
A lambda function is generated to process the CPU data coming from Kinesis and redirected to DynamoDB.

![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/cb6aecdc-295d-451f-8050-4a4040380316)

**Comment by tacho090** [comment]
Is there a pull request for this issue? @XrosHeart05

**Comment by XrosHeart05** [comment]
Yes, this [PR](https://github.com/tachOrg/shell_scripts/pull/2)

**Comment by tacho090** [comment]
Closed due to  https://github.com/tachOrg/shell_scripts/pull/2
