### ISSUE TITLE
Analyze email sending events with Amazon Kinesis Data Analytics

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#7]
Amazon Kinesis Data Analytics enables you to process and analyze streaming data using SQL. You can use Amazon Kinesis Data Analytics to analyze your Amazon SES email sending events.

[In this tutorial](https://docs.aws.amazon.com/ses/latest/dg/event-publishing-kinesis-analytics.html), you first set up an Amazon SES configuration set to publish your email sending events to an Amazon Kinesis Data Firehose delivery stream, and then you send emails through Amazon SES using that configuration set. You then set up Amazon Kinesis Data Analytics to capture the email sending events from the Kinesis Data Firehose stream and use SQL to extract key information from the emails you sent.

**Comment by XrosHeart05** [comment]
Actually trying to understand about Firehose functionality; A CF template for this service was initialized.

**Comment by XrosHeart05** [comment]
For the creation of domains, mails and firehose I am needing permissions for their respective creations.
On the other hand I wanted to add IaC from the mail section, however I find that for the Domain section, CF does not have support for this service currently.

**Comment by XrosHeart05** [comment]
Currently we are having problems in step 4.3 of the tutorial, because the application indicates that it needs a JAR (Java) or .zip file to continue with the flow, however, the generated files are flat and do not even have any kind of extension

**Comment by tacho090** [comment]
Closed due to deprecated tutorial.
